const codenames = [
  "Nightingale",
  "Kraken",
  "Ravenclaw",
  "Shadowfang",
  "Viperstrike",
  "Stormcaller",
  "Ironclad",
  "Frostbite",
  "Bladewing",
  "Widowmaker",
  "Thunderfury",
  "Hellfire",
  "Ghostblade",
  "Abyssfang",
  "Dragon’s Wrath",
  "Bloodthorn",
  "Eclipse Edge",
  "Phoenix Talon",
  "Silent Reaper",
  "Venomfang",
  "Gravekeeper",
  "Doombringer",
  "Soulrender",
  "Darkbane",
  "Starfall",
  "Nightshade",
  "Deathspike",
  "Flameseeker",
  "Lunarscythe",
  "Skybreaker",
];

export { codenames };
